global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'telegram-webhook'
  repeat_interval: 4h
  group_interval: 5m
  group_wait: 30s

receivers:
  - name: 'telegram-webhook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
